Modify versioned-symbol gate to fail if the system libstdc++ requires a newer GLIBCXX/CXXABI than the built one provides:

diff --git a/gcc/13/Containerfile b/gcc/13/Containerfile
--- a/gcc/13/Containerfile
+++ b/gcc/13/Containerfile
@@ -136,16 +136,60 @@ RUN set -ex; \
 	apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false
 
 # gcc installs .so files in /usr/local/lib64 (and /usr/local/lib)...
-RUN set -ex; \
-# this filename needs to sort higher than all the architecture filenames ("aarch64-...", "armeabi...", etc)
-	{ echo '/usr/local/lib64'; echo '/usr/local/lib'; } > /etc/ld.so.conf.d/000-local-lib.conf; \
-	ldconfig -v; \
-	# the libc created by gcc might be too old for a newer Debian
-	# check that the Debian libstdc++ doesn't have newer requirements than the gcc one
-	deb="$(readlink -ve /usr/lib/*/libstdc++.so* | head -1)"; \
-	gcc="$(readlink -ve /usr/local/lib*/libstdc++.so | head -1)"; \
-# using LD_PRELOAD to make sure "abidiff" itself doesn't fail with the exact error we're trying to test for 😂😭
-	LD_PRELOAD="$deb" abidiff --no-added-syms "$deb" "$gcc"
+# RUN set -ex; \
+# # this filename needs to sort higher than all the architecture filenames ("aarch64-...", "armeabi...", etc)
+# 	{ echo '/usr/local/lib64'; echo '/usr/local/lib'; } > /etc/ld.so.conf.d/000-local-lib.conf; \
+# 	ldconfig -v; \
+# 	# the libc created by gcc might be too old for a newer Debian
+# 	# check that the Debian libstdc++ doesn't have newer requirements than the gcc one
+# 	deb="$(readlink -ve /usr/lib/*/libstdc++.so* | head -1)"; \
+# 	gcc="$(readlink -ve /usr/local/lib*/libstdc++.so | head -1)"; \
+# # using LD_PRELOAD to make sure "abidiff" itself doesn't fail with the exact error we're trying to test for 😂😭
+# 	LD_PRELOAD="$deb" abidiff --no-added-syms "$deb" "$gcc"
+
+RUN set -eux; \
+  # Make sure /usr/local libs are on the path for ld.so
+  { echo '/usr/local/lib64'; echo '/usr/local/lib'; } > /etc/ld.so.conf.d/000-local-lib.conf; \
+  ldconfig -v; \
+  \
+  # Locate system vs built libstdc++
+  deb="$(readlink -ve /usr/lib/*/libstdc++.so* | head -1)"; \
+  gcc="$(readlink -ve /usr/local/lib*/libstdc++.so | head -1)"; \
+  echo "System libstdc++: $deb"; \
+  echo "Built   libstdc++: $gcc"; \
+  \
+  # Ensure objdump is available (binutils)
+  command -v objdump >/dev/null 2>&1 || { \
+    apt-get update; \
+    apt-get install -y --no-install-recommends binutils; \
+    rm -rf /var/lib/apt/lists/*; \
+  }; \
+  \
+  # Highest provided (exports) in a lib: GLIBCXX_* / CXXABI_* versions
+  max_provided_ver() { \
+    objdump -T "$1" \
+      | awk '/GLIBCXX_|CXXABI_/{print $NF}' \
+      | sed 's/.*@@\|.*@//' \
+      | sort -V | uniq | tail -n1; \
+  }; \
+  # Highest required (undefined imports) from a lib: what this lib needs at runtime
+  max_required_ver() { \
+    objdump -T "$1" \
+      | awk '/UND/ && /GLIBCXX_|CXXABI_/{print $NF}' \
+      | sed 's/.*@@\|.*@//' \
+      | sort -V | uniq | tail -n1; \
+  }; \
+  \
+  deb_req="$(max_required_ver "$deb")"; \
+  gcc_prov="$(max_provided_ver "$gcc")"; \
+  echo "System libstdc++ requires up to: ${deb_req:-none}"; \
+  echo "Your GCC build provides up to: ${gcc_prov:-none}"; \
+  \
+  # Fail if the system requires a newer version than our built lib provides
+  if [ -n "${deb_req:-}" ] && [ "$(printf '%s\n%s\n' "$gcc_prov" "$deb_req" | sort -V | tail -n1)" != "$gcc_prov" ]; then \
+    echo >&2 "ERROR: System requires $deb_req but your libstdc++ provides only $gcc_prov"; \
+    exit 1; \
+  fi
 
 # ensure that alternatives are pointing to the new compiler and that old one is no longer used
 RUN set -ex; \
